### ISSUE TITLE
If the timestamp of the files is exactly the same the sort function error

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/dds-blog#3]

**Comment by kpanic** [comment]
Hey @rizafahmi thanks for merging #2 :100: :)
Could you provide more info about this bug? I wasn't able to reproduce, thanks a lot!
Maybe I'll start to write some unit test to exercise myself. I am still learning  the language :blush:

**Comment by rizafahmi** [comment]
I tried to copy 3 or 4 markdown files into contents directory. The modified datetime is excatly the same. When I run the app, and hit `/` it got error. Try to touch two markdown files inside contents and you've got the error.

I did sort by newest before you, but just using *nix system `ls -t`. Here the code:
`{files, _} = System.cmd("ls", ["-t", "./priv/contents"])`

`file_lists = String.split(files, "\n") |> Enum.filter(fn(item) -> item != "" end)`

**Comment by kpanic** [comment]
Yes, I  noticed that you were  using the system `ls` and I wanted to try another approach
Weird, I created these files:

```
2015-02-01 11:35:13.379797372 +0100 another_file.md
2015-02-01 11:35:13.379797372 +0100 another_file2.md
2015-02-01 11:39:15.835786562 +0100 filename.md
2015-02-01 11:39:15.835786562 +0100 basicfp.md
```

I also tried 4 files with the same timestamps

```
2015-02-01 11:42:35.303777669 +0100 filename.md
2015-02-01 11:42:35.303777669 +0100 basicfp.md
2015-02-01 11:42:35.303777669 +0100 another_file.md
2015-02-01 11:42:35.303777669 +0100 another_file2.md
```

No success to reproduce
And I got no errors, is there a traceback produced in iex?
Thanks

**Comment by rizafahmi** [comment]
This is the error message:
`18:47:26.080 [error] Error in process <0.256.0> with exit value: {[{reason,function_clause},{mfa,{'Elixir.DdsBlog.Handler',handle,2}},{stacktrace,[{'Elixir.Files.Sort',sort,[[#{filename=><<26 bytes>>,timestamp=>1422513250}]],[{file,"lib/dds_blog/files_sort.ex"},{line,21}]},{'Elixir.Files.Sort',sort,1,[{file,"li..`

And this is the contents file.

```
ll priv/contents/
total 124K
-rw-r--r-- 1 riza users 6.8K Jan 15 11:58 basicfp.md
-rwxr-xr-x 1 riza users  22K Jan 29 06:34 elixirdose_flatfileblog (another copy).md*
-rwxr-xr-x 1 riza users  22K Jan 29 06:34 elixirdose_flatfileblog (copy).md*
-rwxr-xr-x 1 riza users  22K Jan 29 06:34 elixirdose_flatfileblog.md*
-rw-r--r-- 1 riza users  28K Feb  1 18:44 filename.md
```
